spring.application.name=springwithoutweb

#Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:projeto_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update

#Configuração customizada do nosso sistema
#Tempo em milissegundos (10000 = 10 segundos)
app.system.read-interval=10000
app.system.input-directory=./input