# Nome da aplicacao
spring.application.name=Web Vaccination System

# Configuracoes do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:vaccinationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=12345

# Habilita o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra o SQL gerado no terminal
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Atrasa a execução do data.sql até que o JPA/Hibernate tenha criado as tabelas
spring.jpa.defer-datasource-initialization=true